/*
	Description: 	Do not edit this file manually
	Author:			SDL Compiler
*/

#ifndef SDL_TESTSVR_H
#define SDL_TESTSVR_H

#ifndef SDL_TESTSVR_BASE_H
#include "sdl_testsvr_base.h"
#endif

#ifndef VENUS_CONNECTION_H
#include <venus/Connection.h>
#endif

#pragma pack(1)

namespace testsvr {


class TestSvr : public cerl::Connection, public TestSvrBase
{
public:
	TestSvr()
	{}

	TestSvr(const cerl::Connection& conn)
		: cerl::Connection(conn)
	{}

	bool cerl_call test(cerl::ScopedAlloc& alloc,
		_TestResult& _result,
		const MsgData& val
		)
	{
		return cerl::Connection::dbg_call(this, alloc, _result, (cerl::FID)code_test, val);
	}
};

class SyncTestSvr : public TestSvrBase
{
private:
	cerl::SyncConnection& m_conn;

public:
	SyncTestSvr(cerl::SyncConnection& conn)
		: m_conn(conn)
	{}

	bool cerl_call test(cerl::ScopedAlloc& alloc,
		_TestResult& _result,
		const MsgData& val
		)
	{
		return m_conn.dbg_call(this, alloc, _result, (cerl::FID)code_test, val);
	}
};

} //namespace

#pragma pack()

#endif /* SDL_TESTSVR_H */ 
